drugs/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
app_name = 'drugs'

urlpatterns = [

    url('drugprofile/', views.Drug_Profile, name="drug"),
	url('professional/', views.professional, name="professional"),
    url('', views.Drug, name='Drugs'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),

   path('', include('drugs.urls', namespace='Drugprofile')),
]

drugs/models.py
from django.db import models

# Create your models here.

drugs/views.py
from django.shortcuts import render
import requests
from django.http import JsonResponse
from rest_framework import status
from pymongo import MongoClient
import json
import re
from django.utils.safestring import mark_safe


# Create your views here.








def Drug(request):
    return render(request, 'dos.html')


def Drug_Profile(request):
        drug = {}
        client = MongoClient('localhost', 27017)
        # creating database
        db = client['config']
        # creating acollection
        collec = db['drugs']
        generic_names = list(collec.distinct('product_scientific_name'))
        brand_names = list(collec.distinct('product_name_en'))
        if 'drugname' in request.GET:
            drugname = request.GET['drugname']
            url_brand = 'https://api.fda.gov/drug/label.json?search=openfda.brand_name:' + drugname
            url_generic = 'https://api.fda.gov/drug/label.json?search=openfda.generic_name:' + drugname
            response_brand = requests.get(url_brand)
            response_generic = requests.get(url_generic)
            message = 'Drug NOT Found'
            r = requests.get('https://api.fda.gov/drug/label.json?search=openfda.brand_name:' + drugname)
            if drugname in generic_names:
                drugname = drugname.upper()
                search_request = requests.get(
                    'https://api.fda.gov/drug/label.json?search=openfda.generic_name:' + drugname)
                cursor = list(collec.aggregate([{"$unwind": "$product_scientific_name"},
                                                {"$match":
                                                     {'product_scientific_name': drugname}},
                                                {"$group": {"_id": "$product_scientific_name",
                                                            "product_name_en": {
                                                                "$addToSet": "$product_name_en"}}}]))
                try:
                    message1 = "feature not found"

                    # # Convert dict to string
                    # data = json.dumps(drugs)
                    #
                    # mes = data.split(',')
                    # lst = '\n'.join(mes)
                    # print(lst)
                    #
                    # message = mes
                    # context = {"message": message,
                    #            "interact": interact,
                    #            "lst": lst,
                    #            }
                    try:
                        interaction = search_request.json()['results'][0]["drug_interactions"]
                        interact = json.dumps({" interaction": interaction})
                        my_string = interact
                        remove = ['{" interaction": ["', '"]}', '(7.2)"]}', ' [ see Warnings and Precautions ( 5 .6)',
                                  '[ see Warnings and Precautions ( 5 . 6 )]',
                                  '[ see Warnings and Precautions ( 5 . 11 )]',
                                  '[ see Warnings and Precautions ( 5 . 2 )]']

                        for value in remove:
                            my_string = my_string.replace(value, '')
                        interact = re.split(r'(?<=[;.])(?<!\d.)\s', my_string)
                    except:
                        interact = "feature not found"

                    try:
                        clinical_pharmacology = search_request.json()['results'][0]["clinical_pharmacology"],
                        clinical_pharmacology = json.dumps({"clinical_pharmacology": clinical_pharmacology})
                        my_string = clinical_pharmacology
                        remove = ['{"clinical_pharmacology": [["', '"]]}']
                        for value in remove:
                            my_string = my_string.replace(value, '')
                        clinical_pharmacology = re.split(r'(?<=[;.])(?<!\d.)\s', my_string)
                    except:
                        clinical_pharmacology = message1

                    try:
                        sideeffects = search_request.json()['results'][0]["adverse_reactions"],
                        sideeffects = json.dumps({"sideeffects": sideeffects})
                        my_string = sideeffects
                        remove = ['{"sideeffects": [["', '"]]}']
                        for value in remove:
                            my_string = my_string.replace(value, '')
                        sideeffects = re.split(r'(?<=[/.])(?<!\d.)\s', my_string)
                    except:
                        sideeffects = message1

                    try:
                        warning = search_request.json()['results'][0]["warnings_and_cautions"],
                        # Convert dict to string
                        warnings = json.dumps({"warning": warning})
                        my_string = warnings
                        remove = ['{"warning": [["', '"]]}']
                        for value in remove:
                            my_string = my_string.replace(value, '')
                        warn = re.split(r'(?<=[/.])(?<!\d.)\s', my_string)
                    except:
                        warning = search_request.json()['results'][0]["warnings"],
                        # Convert dict to string
                        warnings = json.dumps({"warning": warning})
                        my_string = warnings
                        remove = ['{"warning": [["', '"]]}']
                        for value in remove:
                            my_string = my_string.replace(value, '')
                        warn = re.split(r'(?<=[/.])(?<!\d.)\s', my_string)

                    try:
                        precaution = search_request.json()['results'][0]['precautions'],
                        # Convert dict to string
                        precaution = json.dumps({"precaution": precaution})
                        my_string = precaution
                        remove = ['{"precaution": [["', '"]]}']
                        for value in remove:
                            my_string = my_string.replace(value, '')
                        precaution = re.split(r'(?<=[;.])(?<!\d.)\s', my_string)
                    except:
                        precaution = "feature not found"

                    try:
                        pregnancy = r.json()['results'][0]["pregnancy"],
                        pregnancy = json.dumps({" pregnancy": pregnancy})
                        my_string = pregnancy
                        remove = ['{" pregnancy": [["', '"]]}']
                        for value in remove:
                            my_string = my_string.replace(value, '')
                        pregnancy = re.split(r'(?<=[/.])(?<!\d.)\s', my_string)
                    except:
                        pregnancy = "feature not found"

                    try:
                        stop_use = r.json()['results'][0]["stop_use"],
                    except:
                        stop_use = "feature not found"

                    try:
                        description = search_request.json()['results'][0]['description'],
                        # Convert dict to string
                        description = json.dumps({"description": description})
                        my_string = description
                        remove = ['{"description": [["', '"]]}']
                        for value in remove:
                            my_string = my_string.replace(value, '')
                        description = my_string
                    except:
                        description = "feature not found"

                    try:
                        contraindications_to_use = search_request.json()['results'][0]["contraindications"],
                    except:
                        contraindications_to_use = "feature not found"

                    try:
                        purpose = search_request.json()['results'][0]['purpose'],
                    except:
                        purpose = "feature not found"

                    try:
                        dosage = search_request.json()['results'][0]["dosage_forms_and_strengths"]
                    except:
                        dosage = search_request.json()['results'][0]['dosage_and_administration'],

                    try:
                        generic_name = search_request.json()['results'][0]['openfda']['generic_name'],
                    except:
                        generic_name = drugname

                    drug = {

                        "name": drugname,
                        "generic_name": generic_name,
                        'dosage': dosage,
                        "description": description,
                        "Brand_name": cursor[0]['product_name_en'],
                        "purpose": purpose,
                        "precaution": precaution,
                        'usage': search_request.json()['results'][0]["indications_and_usage"],
                        'contraindications_to_use': contraindications_to_use,
                        "stop_use": stop_use,
                        "pregnancy": pregnancy,
                        'sideeffects': sideeffects,
                        'clinical_pharmacology': clinical_pharmacology,
                        'warning': warn,
                        'interaction': interact,
                        'message': message1

                    }

                    return render(request, 'drug.html', {'drug': drug})
                except(TypeError, KeyError):
                    return JsonResponse({"message": "error500"}, status=status.HTTP_200_OK, safe=False)

            elif drugname in brand_names:
                drugname = drugname.upper()
                cursor = collec.find_one({'product_name_en': drugname})
                generics = cursor['product_scientific_name']
                y = cursor["sell_clause"]

drugs/templates/dos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{drug.name}}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
</head>
<p>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    Drugs
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
<!--                    <form method="get">-->
<!--                        <div class="field has-addons">-->
<!--                            <div class="control is-expanded">-->
<!--                                <input class="input" type="text" name="drugname" placeholder="Enter Drug Name">-->
<!--                            </div>-->
<!--                            <div class="control">-->
<!--                                <button class="button is-info" type="submit" >-->
<!--                                    search-->
<!--                                </button>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </form>-->
                </div>
            </div>
        </div>
    </section>
<h2><a href = "{% url 'Drugprofile:drug' %}">consumer</a></h2>
<h2><a href = "{% url 'Drugprofile:professional' %}">professional</a></h2>

drugs/templates/drug.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{drug.name}}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
</head>
<p>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    Drugs
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="get">
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                <input class="input" type="text" name="drugname" placeholder="Enter Drug Name">
                            </div>
                            <div class="control">
                                <button class="button is-info" type="submit" >
                                    search
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
<h2><a href = "{% url 'Drugprofile:professional' %}">professional</a>



{% if drug %}

    <p><strong>{{ drug.name }}</strong>
        <br>
    <br><strong>Generic Name: </strong>{{drug.generic_name}}</p>
    <br><strong>Brand_name:</strong><br>{{drug.Brand_name}}</p>
    <br>

{% if drug.description != drug.message %}
    <br><strong>Description: </strong><br>{{drug.description}}</p>
    <br>
{% endif %}

{% if drug.purpose != drug.message %}
 <br><strong>Purpose: </strong><br>{{drug.purpose}}</p>
    <br>
{% endif %}



       <br><strong>Usage</strong><br>{{drug.usage}}</p>
    <br>

    <br><strong>Dosage </strong><br>{{drug.dosage}}<br>
{% if drug.contraindications_to_use != drug.message %}
    <br><strong>Contraindications to use</strong><br>{{drug.contraindications_to_use}}</p>
<br>
{% endif %}
{% if drug.stop_use != drug.message %}
    <br><strong>Stop Use</strong><br>{{drug.stop_use}}</p>
<br>
{% endif %}
{% if drug.price %}
 <br><strong>Price </strong><br>{{drug.price}}</p>
    <br>
{% endif %}
{% if  drug.sideeffects != drug.message %}
<br><strong>Side Effects</strong><br>
    {% for i in drug.sideeffects %}
    {{ i }}<br>
    {% endfor %}</p>
{% endif %}
<br>
{% if  drug.pregnancy != drug.message %}
 <br><strong>Pregnancy</strong><br>
    {% for i in drug.pregnancy %}
    {{ i }}<br>
    {% endfor %}</p>
{% endif %}


    <br>
    <br><strong>Warnings</strong><br>
    {% for i in drug.warning %}
      {{ i }}<br>
    {% endfor %}</p>
    <br>
{% if  drug.clinical_pharmacology != drug.message %}
     <br><strong>clinical pharmacology</strong><br>
    {% for i in drug.clinical_pharmacology %}
    {{ i }}<br>
    {% endfor %}</p>
{% endif %}

    <br>
{% if  drug.interaction != drug.message%}
    <br><strong>What other drugs will affect </strong><strong>{{drug.name}}</strong><br>
    {% for i in drug.interaction %}
    {{ i }}<br>
    {% endfor %}</p>
{% endif %}



{% endif %}

drugs/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{drug.name}}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
</head>
<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    Drugs
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="get">
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                <input class="input" type="text" name="drugname" placeholder="Enter Drug Name">
                            </div>
                            <div class="control">
                                <button class="button is-info" type="submit" >
                                    search
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% if drug %}
    <p><strong>{{ drug.name }}</strong>
        <br>
    <br><strong>Generic Name: </strong>{{drug.generic_name}}</p>
    <br><strong>Brand Name: </strong>{{drug.brand_name}}</p>
    <br>

    <br><strong>Dosage</strong><br>{{drug.dosage}}</p>
    <br>
       <br><strong>Usage</strong><br>{{drug.usage}}</p>
    <br>
    <br><strong>Contraindications to use</strong><br>{{drug.contraindications_to_use}}</p>
    <br>
    {% if  drug.sideeffects != drug.message%}
    <br><strong>Side Effects</strong><br>
    {% for i in drug.sideeffects %}
    {{ i }}<br>
    {% endfor %}</p>
    {% endif %}

    <br>
    <br><strong>Pregnancy</strong><br>
    {% for i in drug.pregnancy %}
    {{ i }}<br>
    {% endfor %}</p>

    <br>
    <br><strong>Warnings</strong><br>
    {% for i in drug.warning %}
    {{ i }}<br>
    {% endfor %}</p>
    <br>
     <br><strong>clinical pharmacology</strong><br>
    {% for i in drug.clinical_pharmacology %}
    {{ i }}<br>
    {% endfor %}</p>

    <br>
    {% if  drug.interaction != drug.message%}
    <br><strong>What other drugs will affect </strong><strong>{{drug.name}}</strong><br>
    {% for i in drug.interaction %}
    {{ i }}<br>
    {% endfor %}</p>
    {% endif %}

  {% endif %}

drugs/templates/professional.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{drug.name}}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
</head>
<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    Drugs
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="get">
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                <input class="input" type="text" name="drugname" placeholder="Enter Drug Name">
                            </div>
                            <div class="control">
                                <button class="button is-info" type="submit" >
                                    search
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% if drug %}
<!--    <p><strong>{{ drug.name }}</strong>-->
<!--        <br>-->
<!--    <br><strong>Generic Name: </strong>{{drug.generic_name}}</p>-->
<!--    <br><strong>Brand Name: </strong>{{drug.brand_name}}</p>-->
<!--    <br>-->

<!--    <br><strong>Dosage</strong><br>{{drug.dosage}}</p>-->
<!--    <br>-->
<!--       <br><strong>Usage</strong><br>{{drug.usage}}</p>-->
<!--    <br>-->
<!--    <br><strong>Contraindications to use</strong><br>{{drug.contraindications_to_use}}</p>-->
<!--    <br>-->
<!--     <br><strong>Adverse Reactions/Side Effects </strong><br>-->
<!--    {% for i in drug.sideeffects %}-->
<!--    {{ i }}<br>-->
<!--    {% endfor %}</p>-->

<!--    -->

<!--    <br>-->
<!--    <br><strong>Pregnancy</strong><br>-->
<!--    {% for i in drug.pregnancy %}-->
<!--    {{ i }}<br>-->
<!--    {% endfor %}</p>-->

<!--    <br>-->
<!--    <br><strong>Warnings</strong><br>-->
<!--    {% for i in drug.warning %}-->
<!--    {{ i }}<br>-->
<!--    {% endfor %}</p>-->
<!--    <br>-->
<!--     <br><strong>clinical pharmacology</strong><br>-->
<!--    {% for i in drug.clinical_pharmacology %}-->
<!--    {{ i }}<br>-->
<!--    {% endfor %}</p>-->

<!--    <br>-->
<!--    <br><strong>What other drugs will affect </strong><strong>{{drug.name}}</strong><br>-->
<!--    {% for i in drug.interaction %}-->
<!--    {{ i }}<br>-->
<!--    {% endfor %}</p>-->
<!--    <br>-->


   <p><strong>{{ drug.name }}</strong>
        <br>
    <br><strong>Generic Name: </strong>{{drug.generic_name}}</p>
    <br><strong>Brand_name:</strong><br>{{drug.Brand_name}}</p>
    <br>

{% if drug.description != drug.message %}
    <br><strong>Description: </strong><br>{{drug.description}}</p>
    <br>
{% endif %}

{% if drug.purpose != drug.message %}
 <br><strong>Purpose: </strong><br>{{drug.purpose}}</p>
    <br>
{% endif %}



<br><strong>Usage</strong><br>{{drug.usage}}</p>
    <br>

    <br><strong>Dosage </strong><br>{{drug.dosage}}<br>
{% if drug.contraindications_to_use != drug.message %}
    <br><strong>Contraindications to use</strong><br>{{drug.contraindications_to_use}}</p>
<br>
{% endif %}
{% if drug.stop_use != drug.message %}
    <br><strong>Stop Use</strong><br>{{drug.stop_use}}</p>
<br>
{% endif %}
{% if drug.price %}
 <br><strong>Price </strong><br>{{drug.price}}</p>
    <br>
{% endif %}
{% if  drug.sideeffects != drug.message %}
<br><strong>Adverse Reactions/Side Effects</strong><br>
    {% for i in drug.sideeffects %}
    {{ i }}<br>
    {% endfor %}</p>
{% endif %}
<br>
    {% if  drug.overdosage != drug.message%}
     <br><strong>Overdosage</strong><br>{{drug.overdosage}}</p>
    <br>
{% endif %}
<br>
{% if  drug.pregnancy != drug.message %}
 <br><strong>Pregnancy</strong><br>
    {% for i in drug.pregnancy %}
    {{ i }}<br>
    {% endfor %}</p>
{% endif %}
<br>
    {% if  drug.how_supplied != drug.message %}
    <br><strong>How Supplied</strong><br>{{drug.how_supplied}}</p>
    <br>
{% endif %}


    <br>
    <br><strong>Warnings</strong><br>
    {% for i in drug.warning %}
      {{ i }}<br>
    {% endfor %}</p>
    <br>
{% if  drug.clinical_pharmacology != drug.message %}
     <br><strong>clinical pharmacology</strong><br>
    {% for i in drug.clinical_pharmacology %}
    {{ i }}<br>
    {% endfor %}</p>
{% endif %}


    <br>
{% if  drug.interaction != drug.message%}
    <br><strong>What other drugs will affect </strong><strong>{{drug.name}}</strong><br>
    {% for i in drug.interaction %}
    {{ i }}<br>
    {% endfor %}</p>
{% endif %}




<!--{% if  drug.information_for_patients != drug.message%}-->
    <br><strong>Information for patients</strong><br>
      {% for i in drug.information_for_patients %}
    {{ i }}<br>
    {% endfor %}</p>
<!--    {% endif %}-->
    <br>


  {% endif %}